MvcOnlineTicariOtomasyon/Controllers/DenemeController.cs
using MvcOnlineTicariOtomasyon.Models.Siniflar;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class DenemeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }   
        [HttpPost]
        public ActionResult Index(string kod)
        {
            using(MemoryStream ms=new MemoryStream())
            {
                QRCodeGenerator koduret = new QRCodeGenerator();
                QRCodeGenerator.QRCode karekod = koduret.CreateQrCode(kod, QRCodeGenerator.ECCLevel.Q);
                using (Bitmap resim = karekod.GetGraphic(10))
                {
                    resim.Save(ms, ImageFormat.Png);
                    ViewBag.karekodimage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                }
            }
            return View();
        }

        public ActionResult test()
        {
            return View();
        }
    }
}

MvcOnlineTicariOtomasyon/Controllers/TestController.cs
using MvcOnlineTicariOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        Context c = new Context();
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Personel p)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Image/" + dosyaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                p.PersonelGorsel = "/Image/" + dosyaadi + uzanti;
            }
            c.Personels.Add(p);
            c.SaveChanges();
            return View();
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Deneme/Index.cshtml
@{
    Layout = null;
}

<div>
    @using (Html.BeginForm("Index", "Deneme", FormMethod.Post))
    {
        <input type="text" name="kod" />
        <input type="submit" value="Oluştur" />
    }
    <br />
    @if (ViewBag.karekodimage != null)
    {
        <img src="@ViewBag.karekodimage" alt="" style="width:400px; height:400px;" />
    }
</div>

MvcOnlineTicariOtomasyon/Views/Deneme/test.cshtml
@{
    ViewBag.Title = "test";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>test</h2>

@{
    var grfik = new Chart(width: 400, height: 400);
    grfik.AddTitle(text: "Akdeniz Bölgesi Şehirleri");
    grfik.AddLegend(title: "Nufus");
    grfik.AddSeries(
        name: "Deger",
        chartType:"Pie",
        xValue: new[] { "Adana", "Antalya", "Isparta" },
        yValues: new[] { 80, 60, 40 }
                );
    grfik.Write();
}